# Generated by Django 2.1.2 on 2018-11-22 02:25

import contas.models.usuario
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='Nome de Usuário')),
                ('data_expiracao', models.DateField(null=True, verbose_name='Data de Expiração')),
                ('tipo', models.CharField(choices=[('C', 'Coordenador'), ('P', 'Professor'), ('A', 'Aluno')], max_length=1, verbose_name='Tipo de Usuário')),
            ],
            options={
                'db_table': 'USUARIO',
            },
            managers=[
                ('objects', contas.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('ra', models.IntegerField(unique=True, verbose_name='RA')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ALUNO',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'COORDENADOR',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('apelido', models.CharField(max_length=120, verbose_name='Apelido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PROFESSOR',
            },
        ),
        migrations.CreateModel(
            name='AlunoUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'proxy': True,
                'indexes': [],
            },
            bases=('contas.usuario',),
            managers=[
                ('objects', contas.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadorUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'coordenador',
                'verbose_name_plural': 'coordenadores',
                'proxy': True,
                'indexes': [],
            },
            bases=('contas.usuario',),
            managers=[
                ('objects', contas.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'proxy': True,
                'indexes': [],
            },
            bases=('contas.usuario',),
            managers=[
                ('objects', contas.models.usuario.UsuarioManager()),
            ],
        ),
    ]
