# Generated by Django 2.1.2 on 2018-11-22 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=255)),
                ('conteudo', models.TextField(max_length=255)),
                ('tipo', models.TextField(max_length=255)),
                ('extras', models.TextField(max_length=255)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
            options={
                'db_table': 'Atividade',
            },
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('rotulo', models.TextField(max_length=255)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.Atividade')),
            ],
            options={
                'db_table': 'AtividadeVinculada',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=260, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, unique=True, verbose_name='Sigla')),
                ('sobre', models.TextField(null=True, verbose_name='Sobre o curso')),
                ('duracao', models.SmallIntegerField(verbose_name='Semestre')),
                ('tipo_curso', models.CharField(choices=[('TEC', 'Técnico'), ('G', 'Graduação'), ('POS', 'Pós-Graduação'), ('MBA', 'Master of Business Administration')], max_length=3, verbose_name='Tipo de Curso')),
                ('tipo_graduacao', models.CharField(choices=[('B', 'Bacharelado'), ('T', 'Tecnólogo')], max_length=1, verbose_name='Tipo de Graduação')),
                ('matutino', models.BooleanField(verbose_name='Matutino')),
                ('vespertino', models.BooleanField(verbose_name='Vespertino')),
                ('noturno', models.BooleanField(verbose_name='Noturno')),
            ],
            options={
                'db_table': 'CURSO',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('identificador', models.CharField(max_length=30, unique=True, verbose_name='Identificador')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberta'), ('FECHADO', 'Fechada')], max_length=10, verbose_name='Status')),
                ('carga_horaria', models.SmallIntegerField(verbose_name='Carga Horária')),
                ('percentual_pratico', models.SmallIntegerField(verbose_name='Percentual Prático')),
                ('percentual_teorico', models.SmallIntegerField(verbose_name='Percentual Teórico')),
                ('plano_de_ensino', models.TextField(blank=True, verbose_name='Plano de Ensino')),
                ('competencias', models.TextField(blank=True, verbose_name='Competências')),
                ('habilidades', models.TextField(blank=True, verbose_name='Habilidades')),
                ('ementa', models.TextField(blank=True, verbose_name='Ementa')),
                ('conteudo_programatico', models.TextField(blank=True, verbose_name='Conteúdo Programático')),
                ('bibliografia_basica', models.TextField(blank=True, verbose_name='Bibliografia Básica')),
                ('bibliografia_complementar', models.TextField(blank=True, verbose_name='Bibliografia Complementar')),
            ],
            options={
                'db_table': 'DISCIPLINA',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('turma', models.CharField(max_length=1)),
                ('metodologia', models.TextField(max_length=255)),
                ('recursos', models.TextField(max_length=255)),
                ('criterio_avaliacao', models.TextField(max_length=1000)),
                ('plano_aula', models.TextField(max_length=1000)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
            options={
                'db_table': 'DISCIPLINA_OFERTADA',
            },
        ),
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=100)),
                ('resposta', models.TextField(max_length=255)),
                ('dt_entrega', models.DateField()),
                ('status', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('dt_avaliacao', models.DateField()),
                ('obs', models.TextField(max_length=255)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Aluno')),
                ('atividade_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.AtividadeVinculada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
            options={
                'db_table': 'EntregaAtividade',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField(max_length=255)),
                ('referencia', models.TextField(max_length=255)),
                ('conteudo', models.TextField(max_length=255)),
                ('status', models.IntegerField()),
                ('dt_envio', models.DateField()),
                ('dr_resposta', models.DateField()),
                ('resposta', models.TextField(max_length=1000)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor')),
            ],
            options={
                'db_table': 'Mensagem',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('identificador', models.CharField(max_length=30, unique=True, verbose_name='Identificador')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberta'), ('FECHADO', 'Fechada')], max_length=10, verbose_name='Status')),
                ('carga_horaria', models.SmallIntegerField(verbose_name='Carga Horária')),
                ('percentual_pratico', models.SmallIntegerField(verbose_name='Percentual Prático')),
                ('percentual_teorico', models.SmallIntegerField(verbose_name='Percentual Teórico')),
                ('plano_de_ensino', models.TextField(blank=True, verbose_name='Plano de Ensino')),
                ('competencias', models.TextField(blank=True, verbose_name='Competências')),
                ('habilidades', models.TextField(blank=True, verbose_name='Habilidades')),
                ('ementa', models.TextField(blank=True, verbose_name='Ementa')),
                ('conteudo_programatico', models.TextField(blank=True, verbose_name='Conteúdo Programático')),
                ('bibliografia_basica', models.TextField(blank=True, verbose_name='Bibliografia Básica')),
                ('bibliografia_complementar', models.TextField(blank=True, verbose_name='Bibliografia Complementar')),
            ],
            options={
                'db_table': 'SOLICITACAO_MATRICULA',
            },
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculo.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.Professor'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together={('curso', 'disciplina', 'turma', 'ano', 'semestre')},
        ),
    ]
